### ISSUE TITLE
Kastelo.org needs a TLS certificate

### ISSUE THREAD

**Issue by erciccione** [monero-project/kastelo#32]
Right now it hasn't one and will result in a warning from the browser. We link to kastelo.org from getmonero.org/downloads.

See https://certbot.eff.org/

Related issue on Gitlab: https://repo.getmonero.org/monero-project/monero-site/issues/1027

**Comment by maogo** [comment]
It's not needed,this project has failed.

**Comment by michaesc** [comment]
The certificate accompanies new content, neither of which can be installed yet.

**Comment by erciccione** [comment]
@michaesc The problem is that we link to kastelo.org from getmonero, but we have the strict rule to not link to non-https websites. We recently delisted many merchants for this very reason. Kastelo.org is the only exception at the moment and should be really fixed as soon as possible or we will be forced to remove the link until it's fixed. Expecially since historically, Kastelo updates take a considerable amount of time.

> neither of which can be installed yet

Is there any particular reason for this? Installing a certificat should be a matter of minutes.
